db:
  db_name: fluss_db
  engine: django.db.backends.postgresql
  host: db
  password: 37237260f6da98b5fa30538b8be31a37
  port: 5432
  username: snoopylinenburmese
django:
  admin:
    password: admin
    username: admin
  debug: false
  hosts:
  - '*'
  secret_key: f4f0b11148667e4a2678000c334c4d3a
lok:
  issuer: lok
  key_type: RS256
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqY8POOEYyDQJBMSsb3KNulEjXnel/NA7pMKjvFczOaA5XqxqU5ekfm48jOKRQZk1OI5ij+CRzJO4b8L4wcUKcfV70y6wpN5TkR/2msqrcoB9VN8yqiK/Qye6M79YKJSEH84tVRfHnJifVx46eycqH+g+3u1NXwBmWu+ms6Uc6oOJEtBhddRHPOVX/8OUGu7nbkSIZ/a00tM6LDrpYMfB6/nfWYCKGboJwlz6A2PvCBwhYGvp6/HxJm4+Zgr78QQrQdMUpJAhLJKaUG5OR+KmbmtLd1oH7+Tx/5JlWST8wHk93uWG66pkfSms4eeU2i7GPm0Ry1sBHTaAWBHj+mL3V
minio:
  access_key: shaggymauvegecko
  buckets:
   media: flussmedia
  host: minio
  port: '9000'
  protocol: http
  secret_key: 4cba5aa4701998f339531f727052efba
redis:
  host: redis
  port: 6379