activation_days: 7
apps:
  - client_id: soinfosienfoisnseghsggegefoisneofinsef
    client_secret: soinfosienesfseffoisnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.mikroj
    name: MikroJ
    redirect_uris:
      - http://localhost:8090
    scopes:
      - read
      - write
    tenant: johannes
    token: 293j40239j4023023n09nw30d9n203nf03f
    version: latest
  - client_id: gdrgdhgnjsdfsefs
    client_secret: soinfosienesfseff3298zhiub9328ruoisnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.arkitekt
    name: Arkitekt Test Client
    redirect_uris:
      - http://localhost:5634
      - http://localhost:5634/callback
    scopes:
      - read
      - write
    tenant: johannes
    version: latest
    token: 293j40239j4023023n09nj09n49nin3w30d9n203nf03f
  - client_id: snfoinosinefsef
    client_secret: 9noinfpuisenfpsiuenfpiosenfiusef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.orkestrator
    name: orkestrator
    redirect_uris:
      - http://localhost:8090
      - http://localhost:6789/callback
      - http://localhost:6789
      - http://localhost:7890/callback
      - http://localhost:7890
      - http://100.91.169.37:7890/callback
      - http://100.91.169.37:7890
      - http://10.144.196.141:6789/callback
      - http://10.144.196.141:6789
      - http://100.91.169.37:6789
      - http://100.91.169.37:6789/callback
      - http://jhnnsrs-server:6789/callback
      - http://jhnnsrs-server:6789/callback
    scopes:
      - read
      - write
    tenant: johannes
    version: latest
    token: 293j40239j4023023n039j309n309n3093n09nw30d9n203nf03f
  - client_id: soinfosienfsfosefghsegfisnefoisneofinsef
    client_secret: soinfoefsefssdfienfoisnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.doks
    name: doks
    redirect_uris:
      - http://localhost:3000
      - http://localhost:3000/callback
      - http://localhost:3000/doks/callback
    scopes:
      - read
      - write
    tenant: johannes
    version: latest
    token: 293j40239j4023023n09nw3oinfinoifnsoifnosineoifnsef0d9n203nf03f
  - client_id: mylittlefakts
    client_secret: mylittlefaktssecret
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.fakts
    name: fakts
    redirect_uris:
      - http://localhost:3456
      - http://localhost:3456/callback
    scopes:
      - read
      - write
    tenant: johannes
    version: latest
    token: 09j039j4r09n3409in09n09n0909209n409n09n3093n3
  - client_id: soinfosienfoaswdasdasdisnefoisneofinsef
    client_secret: soinfosiengeesegegfoisnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.mikromanager
    name: MikroManager
    redirect_uris:
      - http://localhost:8090
    scopes:
      - read
      - write
    tenant: johannes
    version: latest
    token: 304n03940p39m4f09o304fo9m0394mf039n4f039n4f093n4f
  - client_id: soinfosienfoissgsegsegtbsynefoisneofinsef
    client_secret: soinfosienfoissdfsdfnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.mikro-napari
    name: napari
    redirect_uris:
      - http://localhost:6767/
      - http://localhost:6767
    scopes:
      - read
      - write
    tenant: johannes
    version: latest
    token: 093j4093n4f09m3094mf09m309mf09mf094n09enf09n23
  - client_id: sdfsfshrhsdbse4gsrgs4rgdrgsrdgedrg
    client_secret: ffesefnoweirnw9oinr0wnrosienfoin
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.mikroj
    name: mikroj
    redirect_uris:
      - http://localhost:6767/
      - http://localhost:6767
    scopes:
      - read
    tenant: johannes
    version: v0.0.1
    token: 0394mr039m4f093m40f90934nf09n309m2039d029n3f092n3f0293fn
  - client_id: fsefgsdfoina9oiwendaosinaswdaw
    client_secret: ffesefnoweirnw9fesoienfspieounfspoeinoinr0wnrosienfoin
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.gucker
    name: gucker
    redirect_uris:
      - http://localhost:6767/
      - http://localhost:6767
    scopes:
      - read
    tenant: johannes
    version: latest
    token: 2039rn0293md02m3f0pm2p30omr02oin3f0ß92m30f9n2039fn2039fn
  - client_id: 09j09sn09nf0s9ne0f9ns09enf0s9enfsef
    client_secret: 09049n0ne0fsinme0n309n2039n4029340293m0293m0293f
    client_type: private
    grant_type: client-credentials
    identifier: github.io.jhnnsrs.reaktor
    name: gucker
    scopes:
      - read
    tenant: johannes
    version: latest
    token: sf09js09e0f9se0f9ns0e9nfsef

db:
  db_name: lok_db
  engine: django.db.backends.postgresql
  host: db
  password: a649ca339098a6eeba4dcf39b835d47b
  port: 5432
  username: 
deployment:
  name: Default
django:
  admin:
    password: admin
    username: admin
  debug: false
  hosts:
    - "*"
  secret_key: e156a1205e1b6b29561d04a013972748
groups: 
  - name: jo
    description: x
minio:
  access_key: 1c7fa60b68ba9e082a0001c251da273b
  buckets:
    media: lokmedia
  host: minio
  port: "9000"
  protocol: http
  secret_key: d29b573f6f6c6fe870508505294f4141
private_key:  |
  -----BEGIN PRIVATE KEY-----
  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDUnnA1AQ846uES
  3NzSBmBPAl2cFwDaxDQWrdS+SoX7sogTzinAv024qXUIl3P1MPCNRODhdLv84D85
  xBnXYwhJsW6AWSrZhiM6t/SvJRn34gEH/RJrXB5p/iq0gQHJ5QGQwN4XaLq6VvTl
  t7fLkCljv5KVYIZcFyjKK+bMefBqEnRbQDKUm/hefuLVoDgOMiRVu70O5FdmIMiy
  bqppqY6IxibtbZ0eR1h+7Tr3/6uBI46692QmLn7zGdYpX8WkOu/BWWouR+LtLJcz
  5FyerDymxtLOQhiu2LPaqosV+lUrJ74Ni1G0mocTWnN6ardpSqQXbZDQFMN04H8T
  80qh1vrvAgMBAAECggEAEYBulsOyOmqF1xpRyFgOBXLvEbIzDSRUGqnPIVAxHI7i
  9KkRIXSd3ogpwhNK0Ea/BmHtFkyYTNszWSXzRUTkTGyhPp9tujTNzD+S500+iKZp
  6fvC+w4SKCzBMdU3YyR0BIkGacGNMq7bFIMS9ga1NtNw1YBPObVjqNYETECdXEhn
  f7629IjtfqhvWTl56wrXRnxucKNIrWgRyismRyO1fiSVCn42EoepzekRJiPcYWhC
  lDgd3YwX2lNbIbfxAc/6wBY3ipgcFz0kdbfjl4udwFgHJdPRKQFkh6ZW6/58IPLs
  TexHMWny8ZBVGvyV8XAXB6QhMjRD7fEJs1OREcxgwQKBgQDzJJRp4pY/dxdlEcw1
  7Kgokr+ZNKtkjwqgZJgD3lzF4Ai+at1LfwwieZcDFI2MA8aRh4QX+xUvgLOCyNTA
  RWTRmgIdJ2+Vsy86CKuT0wPaMZGjmBjaXpVeU+GBw9v+8XypUqWBRnCEnkrEib1H
  xqYjljGTfDlzjBgYqWU9vzRKTQKBgQDf3KfsOhBBdyF65vfsqDW4oUZQiQaFeQdD
  Z6wcP6iP4RSSsXvrFelB55bM/uvdsIUq7JV+AuQoi885s2karFyLfDTl+xfDUtxJ
  ayxyhNSM6l30uR7qL35LWnwqPPtnlrlB/jEeXWfvsEFaH8xlOdSRGE4sGgUIr7p/
  Q9XYfoiAKwKBgQDv7/wplXnRfVNv4KVV3YmAKHi81nYAUQwahcphnvCMMG5QgqKI
  2wH9j2GPn5ujPSKaAFJBW/xnGSmMeWVBq/k2wjUt0fnSj7WeHmo7AXR+wIXJG9IC
  xG3AXSRfawlRR7tOWImMzhdBN/fuhUJtb0IKQjAALAmB1hD9XUTULziJzQKBgCor
  DXKhCVjbkPHuufrZQK1Tq8QV26Wew7B9wdzcXOslUdPEHPyOdw7UCgL5bgKncp5A
  THSdJM9CbrmGwyCkIRahQfGkV7iSTi6CQrAbt1IH/8TObjVc1uRo2gS20gCUUrdM
  o4H9xEtRHy5T2ROkThc6xdbm29XkDDRW2dxbEWlbAoGABAB78fhIc8kNCCeLU5pL
  /I8cpEL0IIroc2D98BzNgxqXLLkdvnaOLQE9sI+Nd3Ia5jNI6KBGifdEqUujfPhL
  h9sQsNQ0sls5MsoSIl+u45JazhwKD7hAbEU3LIK3KD8CM44pJ0ZOvqSqT2zzbIB9
  tN4Wx01d7gv4OYP/AJl6aXI=
  -----END PRIVATE KEY-----

public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUnnA1AQ846uES3NzSBmBPAl2cFwDaxDQWrdS+SoX7sogTzinAv024qXUIl3P1MPCNRODhdLv84D85xBnXYwhJsW6AWSrZhiM6t/SvJRn34gEH/RJrXB5p/iq0gQHJ5QGQwN4XaLq6VvTlt7fLkCljv5KVYIZcFyjKK+bMefBqEnRbQDKUm/hefuLVoDgOMiRVu70O5FdmIMiybqppqY6IxibtbZ0eR1h+7Tr3/6uBI46692QmLn7zGdYpX8WkOu/BWWouR+LtLJcz5FyerDymxtLOQhiu2LPaqosV+lUrJ74Ni1G0mocTWnN6ardpSqQXbZDQFMN04H8T80qh1vrv
redis:
  host: redis
  port: 6379
scopes:
  can_assign: Can Assign Nodes
  can_create: Can Create Nodes
  can_create_identifier: Can create new identifier for the platform
  can_forward_bounce:
    Can reserve and assign to Nodes mimicking other Users (only
    backend and admin)
  can_provide: Can Provide Nodes
  can_template: Can Template Nodes
  introspection: Introspect the Token scope
  provider: Can act as a provider
  read: Reading all of your Data
  write: Writing to all of your Data
  read_starred: Reading all of your shared Data
token_expire_seconds: 604800
users: 
  - username: johannes
    password: johannes
    groups: 
      - jo 
  - username: karl
    password: schmarl
    groups: 
      - jo 
      - flo 
      - fuck 
