activation_days: 7
apps:
  - client_id: gdrgdhgnjsdfsefs
    client_secret: soinfosienesfseff3298zhiub9328ruoisnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.arkitekt
    name: Arkitekt Test Client
    redirect_uris:
      - http://127.0.0.1/
    scopes:
      - read
      - write
    tenant: admin
    version: latest
    token: 293j40239j4023023n09nj09n49nin3w30d9n203nf03f
  - client_id: snfoinosinefsef
    client_secret: 9noinfpuisenfpsiuenfpiosenfiusef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.orkestrator
    name: orkestrator
    redirect_uris:
      - http://127.0.0.1/
      - http://127.0.0.1/callback
      - http://localhost:8010/callback
      - http://localhost:8010/
    scopes:
      - read
      - write
    tenant: admin
    version: latest
    token: 293j40239j4023023n039j309n309n3093n09nw30d9n203nf03f
  - client_id: soinfosienfsfosefghsegfisnefoisneofinsef
    client_secret: soinfoefsefssdfienfoisnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.doks
    name: doks
    redirect_uris:
      - http://127.0.0.1/callback
      - https://arkitekt.live
      - https://arkitekt.live/callback
    scopes:
      - read
      - write
    tenant: admin
    version: latest
    token: 293j40239j4023023n09nw3oinfinoifnsoifnosineoifnsef0d9n203nf03f
  - client_id: soinfosienfoaswdasdasdisnefoisneofinsef
    client_secret: soinfosiengeesegegfoisnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.mikromanager
    name: MikroManager
    redirect_uris:
      - http://127.0.0.1/
    scopes:
      - read
      - write
    tenant: admin
    version: latest
    token: 304n03940p39m4f09o304fo9m0394mf039n4f039n4f093n4f
  - client_id: soinfosienfoissgsegsegtbsynefoisneofinsef
    client_secret: soinfosienfoissdfsdfnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.mikro-napari
    name: napari
    redirect_uris:
      - http://127.0.0.1/
    scopes:
      - read
      - write
    tenant: admin
    version: latest
    token: 093j4093n4f09m3094mf09m309mf09mf094n09enf09n23
  - client_id: sdfsfshrhsdbse4gsrgs4rgdrgsrdgedrg
    client_secret: ffesefnoweirnw9oinr0wnrosienfoin
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.mikroj
    name: mikroj
    redirect_uris:
      - http://127.0.0.1/
      - http://127.0.0.1/
    scopes:
      - read
    tenant: admin
    version: v0.0.1
    token: 0394mr039m4f093m40f90934nf09n309m2039d029n3f092n3f0293fn
  - client_id: fsefgsdfoina9oiwendaosinaswdaw
    client_secret: ffesefnoweirnw9fesoienfspieounfspoeinoinr0wnrosienfoin
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.gucker
    name: gucker
    redirect_uris:
      - http://127.0.0.1/
    scopes:
      - read
    tenant: admin
    version: latest
    token: 2039rn0293md02m3f0pm2p30omr02oin3f0ß92m30f9n2039fn2039fn

db:
  db_name: lok_db
  engine: django.db.backends.postgresql
  host: db
  password: 37237260f6da98b5fa30538b8be31a37
  port: 5432
  username: snoopylinenburmese
deployment:
  name: Default
django:
  admin:
    password: admin
    username: admin
  debug: false
  hosts:
    - "*"
  secret_key: e0179e1e5c82e7c615bd4b727f73a457
groups: 
  - name: jo
    description: x
minio:
  access_key: breezyivorytapir
  buckets:
    media: lokmedia
  host: minio
  port: "9000"
  protocol: http
  secret_key: 5df6730e9764e16072eb2bda9d35c87f
private_key:  |
  -----BEGIN PRIVATE KEY-----
  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCqY8POOEYyDQJB
  MSsb3KNulEjXnel/NA7pMKjvFczOaA5XqxqU5ekfm48jOKRQZk1OI5ij+CRzJO4b
  8L4wcUKcfV70y6wpN5TkR/2msqrcoB9VN8yqiK/Qye6M79YKJSEH84tVRfHnJifV
  x46eycqH+g+3u1NXwBmWu+ms6Uc6oOJEtBhddRHPOVX/8OUGu7nbkSIZ/a00tM6L
  DrpYMfB6/nfWYCKGboJwlz6A2PvCBwhYGvp6/HxJm4+Zgr78QQrQdMUpJAhLJKaU
  G5OR+KmbmtLd1oH7+Tx/5JlWST8wHk93uWG66pkfSms4eeU2i7GPm0Ry1sBHTaAW
  BHj+mL3VAgMBAAECggEAFELSuMXmSvNTDk97cc+1u2N0mfcUGeUl1MLNg8iS1wR2
  mCQngAcqxnBn/+cvWsQfcyg2cWEDbJG6oqXo57fAFP2veepyKWCLmu2Ykubx/FQq
  Bach9jFUvr4UWLv4NrKdj+V87wHnNvZJjFkzc1xJcgvhLJbg3TFhmZP0wHPo3Was
  U6NP1jZo7iipGH4C3WFFxEGUe31SdzZPJlSZi/EvshaiYET73h0eAOtoJvWTvMg1
  G13wIln39GtDdTs6PycpGTHyziYSQSPCw2FQz/ByIKNXhFY0XS2YY2RkC+h7Qkrx
  EQes/3fJmvWaLrq9fENWc7Dp2YoocVDQC35I0lp/DQKBgQDgs+GCuiqcza1eoVfJ
  7Vml1P5xE4jQ175PdeSs5X1LCERgeuc7tJat/fZZW6GvJ4wzcaM66sxDtx61LebY
  BlstyYfXEs74JT8CTYYDuD8+RGp7C/5miO6foXpMpIpa2+CG4Od2cc2Vo1WaXrg3
  K4I7Sju1tSSD1SU5kEYgE5puVwKBgQDCH0WkeATxGDoHsOJARcJKgaaKnw0W0Y4N
  7SDbyz7CcheIwjcZPcF87yY7Gg5P+aXm0Uct9moG4+ppdz+LjzIIxYUGhkGaRnvV
  xqnsLvYoIHIBTao5weH916fHxf8sggcTlivk8No6J6gKbP4mToysmptkeyRTITUA
  xqTxpkLBswKBgQCST25KQdAXU7FMib/w4pRZ72tR04dlfOUVNk2U6sT/gz2KmNxR
  uw/V8SRkIM8Rjq2ynY7MgTBJ80WScXX7OYBLOwsxVrTfTNlPNY1KhMDhWYj/39ph
  h03hMTLCDu1rpfn3uR/dttJHWhgWMRDAE5tz4a0pbu58zN+1MKUIo9sNdwKBgFBG
  2mf/chu55xWTIp1tu8FQCG0/BQywsEw2CeabEGMdB3p4xoxbq45c37SFO/H6zY68
  cPEi/AnJawEeXVr7ZreV50MhdjO0fjWTqGWRrh49/KdpVMH52dk9u5az3KitRPvm
  mFRe/gAasjVNiXSR+z7N2QEeo5D1JJQjkcaU+PpdAoGAOfVWu3nKjlXHgo5O2HZq
  WDPIuV5jiqrMCqhYBaQMLwRvvVZc6Smv/iOCLu7zmLRc4vgVT6cGlgd3moFVOJyo
  u1Ej56+t8Z8VO4oWfSqZjDkestUT9YZKLvYaOgTpTg+nYvISGXT7sF14amNRrWc4
  OkBBO3mObSi0KUvQMwP00eo=
  -----END PRIVATE KEY-----

public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqY8POOEYyDQJBMSsb3KNulEjXnel/NA7pMKjvFczOaA5XqxqU5ekfm48jOKRQZk1OI5ij+CRzJO4b8L4wcUKcfV70y6wpN5TkR/2msqrcoB9VN8yqiK/Qye6M79YKJSEH84tVRfHnJifVx46eycqH+g+3u1NXwBmWu+ms6Uc6oOJEtBhddRHPOVX/8OUGu7nbkSIZ/a00tM6LDrpYMfB6/nfWYCKGboJwlz6A2PvCBwhYGvp6/HxJm4+Zgr78QQrQdMUpJAhLJKaUG5OR+KmbmtLd1oH7+Tx/5JlWST8wHk93uWG66pkfSms4eeU2i7GPm0Ry1sBHTaAWBHj+mL3V
redis:
  host: redis
  port: 6379
scopes:
  can_assign: Can Assign Nodes
  can_create: Can Create Nodes
  can_create_identifier: Can create new identifier for the platform
  can_forward_bounce:
    Can reserve and assign to Nodes mimicking other Users (only
    backend and admin)
  can_provide: Can Provide Nodes
  can_template: Can Template Nodes
  introspection: Introspect the Token scope
  provider: Can act as a provider
  read: Reading all of your Data
  write: Writing to all of your Data
  read_starred: Reading all of your shared Data
token_expire_seconds: 604800
users: 
  - username: johannes
    password: johannes
    groups: 
      - jo 
  - username: karl
    password: schmarl
    groups: 
      - jo 
      - flo 
      - fuck 
