activation_days: 7
apps:
  - client_id: gdrgdhgnjsdfsefs
    client_secret: soinfosienesfseff3298zhiub9328ruoisnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.arkitekt
    name: Arkitekt Test Client
    redirect_uris:
      - http://127.0.0.1/
    scopes:
      - read
      - write
    tenant: johannes
    version: latest
    token: 293j40239j4023023n09nj09n49nin3w30d9n203nf03f
  - client_id: snfoinosinefsef
    client_secret: 9noinfpuisenfpsiuenfpiosenfiusef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.orkestrator
    name: orkestrator
    redirect_uris:
      - http://127.0.0.1/
      - http://127.0.0.1/callback
      - http://localhost:8010/callback
      - http://localhost:8010/
    scopes:
      - read
      - write
    tenant: johannes
    version: latest
    token: 293j40239j4023023n039j309n309n3093n09nw30d9n203nf03f
  - client_id: soinfosienfsfosefghsegfisnefoisneofinsef
    client_secret: soinfoefsefssdfienfoisnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.doks
    name: doks
    redirect_uris:
      - http://127.0.0.1/
      - https://arkitekt.live
      - https://arkitekt.live/callback
    scopes:
      - read
      - write
    tenant: johannes
    version: latest
    token: 293j40239j4023023n09nw3oinfinoifnsoifnosineoifnsef0d9n203nf03f
  - client_id: soinfosienfoaswdasdasdisnefoisneofinsef
    client_secret: soinfosiengeesegegfoisnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.mikromanager
    name: MikroManager
    redirect_uris:
      - http://127.0.0.1/
    scopes:
      - read
      - write
    tenant: johannes
    version: latest
    token: 304n03940p39m4f09o304fo9m0394mf039n4f039n4f093n4f
  - client_id: soinfosienfoissgsegsegtbsynefoisneofinsef
    client_secret: soinfosienfoissdfsdfnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.mikro-napari
    name: napari
    redirect_uris:
      - http://127.0.0.1/
    scopes:
      - read
      - write
    tenant: johannes
    version: latest
    token: 093j4093n4f09m3094mf09m309mf09mf094n09enf09n23
  - client_id: sdfsfshrhsdbse4gsrgs4rgdrgsrdgedrg
    client_secret: ffesefnoweirnw9oinr0wnrosienfoin
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.mikroj
    name: mikroj
    redirect_uris:
      - http://127.0.0.1/
      - http://127.0.0.1/
    scopes:
      - read
    tenant: johannes
    version: v0.0.1
    token: 0394mr039m4f093m40f90934nf09n309m2039d029n3f092n3f0293fn
  - client_id: fsefgsdfoina9oiwendaosinaswdaw
    client_secret: ffesefnoweirnw9fesoienfspieounfspoeinoinr0wnrosienfoin
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.gucker
    name: gucker
    redirect_uris:
      - http://127.0.0.1/
    scopes:
      - read
    tenant: johannes
    version: latest
    token: 2039rn0293md02m3f0pm2p30omr02oin3f0ß92m30f9n2039fn2039fn

db:
  db_name: lok_db
  engine: django.db.backends.postgresql
  host: db
  password: 0fb71231a356b6f89ee30955fb306916
  port: 5432
  username: crabbymyrtlespaniel
deployment:
  name: Default
django:
  admin:
    password: admin
    username: admin
  debug: false
  hosts:
    - "*"
  secret_key: 36d5a0ef71479974ccfc0468bbb8ff57
groups: 
  - name: jo
    description: x
minio:
  access_key: chewyfirebrickturtle
  buckets:
    media: lokmedia
  host: minio
  port: "9000"
  protocol: http
  secret_key: 0fb09f260615ae121d76e6ea5bb1b0b6
private_key:  |
  -----BEGIN PRIVATE KEY-----
  MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDyKXkrPchIzpgt
  pDmiWzWZFRVVAmb04hyluxTB3F+NFg5pKkoLrguKtT/v2dzgptpUEdCUfI5+kXAE
  ElZevBJfIuqlI46D/zMJ+Ybwg/iebXE76DTwR6DtnQjP2jc2H9Or5BrUH2koA4Sx
  pJbrLkS/YqkkQdu3Ocnbv2vSHITDR5ApFk8W7Qc1bu9AF0JzShWemMFUmPpVqhu4
  QK4zftDyKVJjVpGxlHhlKhuC0eEp6ZUNR0KZWPci7gyhZEFM5+8DvET1GzUiRMgq
  1wLIb0LKlcsXyBSU/3RJu1+mcVVRzFF1lB9pLop/ggfipggRIexK8q1u95wEXEZ7
  1TlBzC+TAgMBAAECggEAX8pQB+7UfxhZ0hQYSETUGs3gNlRQ7aVTt6sdNuI5WdHT
  uX3k9GHQZvnzZKlFWggmbQLvAw2SQDa/nJy0VZ0Hl2J0dwZtpYEZa2StIA7UFbct
  B4l/B10OJ2/qwG2NUXedf20nv6j9K7rYjnyQxk7zGtGoHpN+mifd1XMO73ogei3b
  qzzlyl2ahIJadbP5Lr2GRhBfAq/2Jdq5Nvq/m4D7Aro54a6TgA3ALlFQbE8k0zku
  Rgyhzty+XrOAsePwtjP7ZQeLYEKR7A3P8vtYhfvVrh7ZNeTc2/ug1uXemasouUyv
  eyeyVh3AroZxFrOBeuAhlASrTGYZ9BEJUmWNebg0oQKBgQD+9h1FJa8JH+LOrOFu
  8XqKNVmaiFzeKuCnB0f/YfMkEMb1YaCgvasXCcrlZy2xQyOb+CumS5eURbaRyVZ5
  1MDKEgAlGB6xNSwI136a/P37jfp3g8B3WR40yF1izquO1aaJc7Q2lqIdWvkaMkLr
  73pqJLGJr7uAKucyNaUyd+bULQKBgQDzJgLdPExcoGGswqA1/lPmOdIKrttduCYr
  9HAbBskxDPDLaQnT5O3DMqwNK3wzq4r8DXSlKCBK7rx7ioxkBsfk016pzKdU5Sjn
  IkDygX6sD6aC+JOTRYNZJ8swyj8EVmk9XRakT7kxGZAAt33FSWo9QoOqHaBMGN1s
  uG7VOSaqvwKBgQDMWxYw4zh9lsojH9x9IR44AvTz8NKG3FU+a46gurC4up3N9lda
  H0wv5hBzeRTdnNPA4tSRsMso9AuWpIskkYuJK45kLQYEwXqvB5KZxagJZc5Y1wiA
  YLTeV67KUJ6fmM2oJE5Q5sG/x7gb8CdFlqhGxWxr0Kf33et7ihYD8qjYbQKBgQCY
  KYB/XP3YtZGKoN3MDFYK7MJSZyzm0Jgqx7TkZPHBXXzPfvNkhI56qppbP4xhdYfr
  xqvps1vKKO8RTRogetHblJ9YGbfZ+/MF+jy0xm80VDL7IX6RGl5hi/KvnNGk8EK5
  4SiLOU0Guh2RJUNzFEeFALwO2K15EdJ3+E975mEZVwKBgDyujUWPQaWR/YXhddJK
  6vO7wrziqx1j70Ihc97YQrQ244f1hmONeQ4drU5P8QKpF9w2Hnzr5M/t8C83MGeB
  y2ejps1jDHajY8L5iATiUz1yET2wecKetb4Tb1DA2sYkBQmoVp1F1SMaRoJHtbyj
  Uq+2z9ffR/hVpS+WXizN4fSo
  -----END PRIVATE KEY-----

public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDyKXkrPchIzpgtpDmiWzWZFRVVAmb04hyluxTB3F+NFg5pKkoLrguKtT/v2dzgptpUEdCUfI5+kXAEElZevBJfIuqlI46D/zMJ+Ybwg/iebXE76DTwR6DtnQjP2jc2H9Or5BrUH2koA4SxpJbrLkS/YqkkQdu3Ocnbv2vSHITDR5ApFk8W7Qc1bu9AF0JzShWemMFUmPpVqhu4QK4zftDyKVJjVpGxlHhlKhuC0eEp6ZUNR0KZWPci7gyhZEFM5+8DvET1GzUiRMgq1wLIb0LKlcsXyBSU/3RJu1+mcVVRzFF1lB9pLop/ggfipggRIexK8q1u95wEXEZ71TlBzC+T
redis:
  host: redis
  port: 6379
scopes:
  can_assign: Can Assign Nodes
  can_create: Can Create Nodes
  can_create_identifier: Can create new identifier for the platform
  can_forward_bounce:
    Can reserve and assign to Nodes mimicking other Users (only
    backend and admin)
  can_provide: Can Provide Nodes
  can_template: Can Template Nodes
  introspection: Introspect the Token scope
  provider: Can act as a provider
  read: Reading all of your Data
  write: Writing to all of your Data
  read_starred: Reading all of your shared Data
token_expire_seconds: 604800
users: 
  - username: johannes
    password: johannes
    groups: 
      - jo 
  - username: karl
    password: schmarl
    groups: 
      - jo 
      - flo 
      - fuck 
