buckets:
  - name: flussmedia
  - name: lokmedia
  - name: lokmedia
  - name: lokmedia
  - name: zarr
  - name: parquet
  - name: mikromedia
  - name: lokmedia
  - name: portmedia
  - name: mikromedianew
  - name: zarrnew
  - name: parquetnew
users: 
  - access_key: breezyivorytapir
    name: lok
    policies:
      - readwrite
    secret_key: 5df6730e9764e16072eb2bda9d35c87f
  - access_key: shaggymauvegecko
    name: fluss
    policies:
      - readwrite
    secret_key: 4cba5aa4701998f339531f727052efba
  - access_key: bumpyorchidcassowary
    name: minio
    policies:
      - readwrite
    secret_key: e8d7b3fa01ab5ca40f21d95c5e03fdf5
  - access_key: wheezybronzeladybird
    name: mikro
    policies:
      - readwrite
    secret_key: 8c6421f40e3a5013d57eaadf20fb6048
  - access_key: squeakyazureslug
    name: port
    policies:
      - readwrite
    secret_key: 2dc733ebc4429521a228c1aa9caa3a52
  - access_key: stealthyambertoucan
    name: rekuest
    policies:
      - readwrite
    secret_key: c3e0fbbe172851e09e5eaf368b753aec