buckets:
  - name: flussmedia
  - name: lokmedia
  - name: lokmedia
  - name: lokmedia
  - name: zarr
  - name: parquet
  - name: mikromedia
  - name: lokmedia
  - name: portmedia
  - name: mikromedianew
  - name: zarrnew
  - name: parquetnew
users: 
  - access_key: chewyfirebrickturtle
    name: lok
    policies:
      - readwrite
    secret_key: 0fb09f260615ae121d76e6ea5bb1b0b6
  - access_key: skankyeggplantspider
    name: fluss
    policies:
      - readwrite
    secret_key: c8b5e6191b3fe4e23b2d727deb2adc36
  - access_key: tackycarmineshrew
    name: minio
    policies:
      - readwrite
    secret_key: d049b81ba8fdaf5e420dd2c2b1622db6
  - access_key: paltryrussetwolverine
    name: mikro
    policies:
      - readwrite
    secret_key: e603c243b1e90ac1bcf8c57a1c28f52c
  - access_key: squirrelykhakiabyssinian
    name: port
    policies:
      - readwrite
    secret_key: 8b5b2c79200d45340f449af4f3e8d256
  - access_key: sunnycyanstingray
    name: rekuest
    policies:
      - readwrite
    secret_key: 4c42cbc45019d4501a6d214eae2cdcf7