db:
  db_name: port_db
  engine: django.db.backends.postgresql
  host: db
  password: 0fb71231a356b6f89ee30955fb306916
  port: 5432
  username: crabbymyrtlespaniel
django:
  admin:
    password: admin
    username: admin
  debug: false
  hosts:
  - '*'
  secret_key: 218ba755fe29d94538ad205fadbb811c
lok:
  issuer: lok
  key_type: RS256
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDyKXkrPchIzpgtpDmiWzWZFRVVAmb04hyluxTB3F+NFg5pKkoLrguKtT/v2dzgptpUEdCUfI5+kXAEElZevBJfIuqlI46D/zMJ+Ybwg/iebXE76DTwR6DtnQjP2jc2H9Or5BrUH2koA4SxpJbrLkS/YqkkQdu3Ocnbv2vSHITDR5ApFk8W7Qc1bu9AF0JzShWemMFUmPpVqhu4QK4zftDyKVJjVpGxlHhlKhuC0eEp6ZUNR0KZWPci7gyhZEFM5+8DvET1GzUiRMgq1wLIb0LKlcsXyBSU/3RJu1+mcVVRzFF1lB9pLop/ggfipggRIexK8q1u95wEXEZ71TlBzC+T
minio:
  access_key: squirrelykhakiabyssinian
  buckets:
   media: portmedia
  host: minio
  port: '9000'
  protocol: http
  secret_key: 8b5b2c79200d45340f449af4f3e8d256
redis:
  host: redis
  port: 6379
virtualizer:
  engine: docker