db:
  db_name: port_db
  engine: django.db.backends.postgresql
  host: db
  password: 37237260f6da98b5fa30538b8be31a37
  port: 5432
  username: snoopylinenburmese
django:
  admin:
    password: admin
    username: admin
  debug: false
  hosts:
  - '*'
  secret_key: 38f0cd8af48653bf9a6b15c248894e5c
lok:
  issuer: lok
  key_type: RS256
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqY8POOEYyDQJBMSsb3KNulEjXnel/NA7pMKjvFczOaA5XqxqU5ekfm48jOKRQZk1OI5ij+CRzJO4b8L4wcUKcfV70y6wpN5TkR/2msqrcoB9VN8yqiK/Qye6M79YKJSEH84tVRfHnJifVx46eycqH+g+3u1NXwBmWu+ms6Uc6oOJEtBhddRHPOVX/8OUGu7nbkSIZ/a00tM6LDrpYMfB6/nfWYCKGboJwlz6A2PvCBwhYGvp6/HxJm4+Zgr78QQrQdMUpJAhLJKaUG5OR+KmbmtLd1oH7+Tx/5JlWST8wHk93uWG66pkfSms4eeU2i7GPm0Ry1sBHTaAWBHj+mL3V
minio:
  access_key: squeakyazureslug
  buckets:
   media: portmedia
  host: minio
  port: '9000'
  protocol: http
  secret_key: 2dc733ebc4429521a228c1aa9caa3a52
redis:
  host: redis
  port: 6379
virtualizer:
  engine: docker