db:
  db_name: fluss_db
  engine: django.db.backends.postgresql
  host: db
  password: a649ca339098a6eeba4dcf39b835d47b
  port: 5432
  username: a649ca339098a6eeba4dcf39b835d47b
django:
  admin:
    password: admin
    username: admin
  debug: false
  hosts:
  - '*'
  secret_key: 121452b04391201397601bb62f77bf6d
lok:
  issuer: lok
  key_type: RS256
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUnnA1AQ846uES3NzSBmBPAl2cFwDaxDQWrdS+SoX7sogTzinAv024qXUIl3P1MPCNRODhdLv84D85xBnXYwhJsW6AWSrZhiM6t/SvJRn34gEH/RJrXB5p/iq0gQHJ5QGQwN4XaLq6VvTlt7fLkCljv5KVYIZcFyjKK+bMefBqEnRbQDKUm/hefuLVoDgOMiRVu70O5FdmIMiybqppqY6IxibtbZ0eR1h+7Tr3/6uBI46692QmLn7zGdYpX8WkOu/BWWouR+LtLJcz5FyerDymxtLOQhiu2LPaqosV+lUrJ74Ni1G0mocTWnN6ardpSqQXbZDQFMN04H8T80qh1vrv
minio:
  access_key: aa9dc7c9e89684bc9d1b2fa8dccd6789
  buckets:
   media: flussmedia
  host: minio
  port: '9000'
  protocol: http
  secret_key: 8715cd7df19d190cf3104b49197ae872
redis:
  host: redis
  port: 6379
virtualizer:
  engine: docker