version: '3.7'

services:
  db:
    environment:
      POSTGRES_MULTIPLE_DATABASES: port_db, mikro_db, lok_db, rekuest_db, fluss_db, mikronew_db
      POSTGRES_PASSWORD: 0fb71231a356b6f89ee30955fb306916
      POSTGRES_USER: crabbymyrtlespaniel
    image: jhnnsrs/daten:prod
    labels:
      - "arkitekt.sss.service=db"
  orkestrator:
    image: jhnnsrs/orkestrator:paper
    ports:
      - 8010:80
    labels:
      - "arkitekt.sss.service=orkestrator"
  fluss:
    depends_on:
    - redis
    - db
    image: jhnnsrs/fluss:paper
    ports:
    - 8040:80
    volumes:
    - ./configs/fluss.yaml:/workspace/config.yaml
    labels:
      - "arkitekt.sss.service=fluss"
  initc:
    depends_on:
      minio:
        condition: service_started
    environment:
      MINIO_HOST: http://minio:9000
      MINIO_ROOT_PASSWORD: 200e759923090cecdc49bc3abf6d7d3f
      MINIO_ROOT_USER: shakypersimmoniguana
    image: jhnnsrs/init:paper
    volumes:
    - ./configs/minio.yaml:/workspace/config.yaml
  lok:
    depends_on:
    - redis
    - db
    image: jhnnsrs/lok:paper
    command: bash run-debug.sh
    ports:
    - 8000:80
    volumes:
    - ./configs/lok.yaml:/workspace/config.yaml
    - ./fakts:/workspace/fakts
    labels:
      - "arkitekt.sss.service=lok"
  mikro:
    depends_on:
    - redis
    - db
    - minio
    image: jhnnsrs/mikro:paper
    command: bash run-debug.sh
    ports:
    - 8030:80
    volumes:
    - ./configs/mikro.yaml:/workspace/config.yaml
    labels:
      - "arkitekt.sss.service=mikro"
  minio:
    command: server /data  --console-address ":9001"
    environment:
      MINIO_ROOT_PASSWORD: 200e759923090cecdc49bc3abf6d7d3f
      MINIO_ROOT_USER: shakypersimmoniguana
    image: minio/minio:RELEASE.2023-02-10T18-48-39Z
    ports:
    - 8060:9000
    - 8061:9001
    volumes:
    - ./data:/data
    labels:
      - "arkitekt.sss.service=s3"
  port:
    depends_on:
    - lok
    - db
    - redis
    image: jhnnsrs/port:paper
    command: bash run.sh
    ports:
    - 8050:80
    volumes:
      - ./configs/port.yaml:/workspace/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "arkitekt.sss.service=port"
  portbridge:
    depends_on:
    - lok
    - db
    - redis
    image: jhnnsrs/port:paper
    command: bash run-worker.sh
    volumes:
      - ./configs/port.yaml:/workspace/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "arkitekt.sss.service=portbrdige"
  rabbitmq:
    command: rabbitmq-server
    image: jhnnsrs/mister:fancy
    labels:
      - "arkitekt.sss.service=rabbitmq"
  redis:
    image: redis:latest
    labels:
      - "arkitekt.sss.service=redis"
  rekuest:
    depends_on:
    - redis
    - db
    - rabbitmq
    image: jhnnsrs/rekuest:paper
    ports:
    - 8020:80
    volumes:
    - ./configs/rekuest.yaml:/workspace/config.yaml
    labels:
    - "arkitekt.sss.service=rekuest"
    