db:
  db_name: rekuest_db
  engine: django.db.backends.postgresql
  host: db
  password: {{postgres_password}}
  port: 5432
  username: {{postgres_user}}
django:
  admin:
    password: {{admin_password}}
    username: {{admin_username}}
  debug: false
  hosts:
  - '*'
  secret_key: {{services.rekuest.django_secret_key}}
lok:
  issuer: lok
  key_type: RS256
  public_key: {{public_key}}
minio:
  access_key: {{services.rekuest.access_key}}
  buckets:
   media: rekuestmedia
  host: minio
  port: '9000'
  protocol: http
  secret_key: {{services.rekuest.secret_key}}
redis:
  host: redis
  port: 6379
rabbitmq:
  host: rabbitmq
  password: guest
  port: 5672
  username: guest
  v_host: ''
